version: '3'
services:

  db:
    image: postgres:latest 
    hostname: db
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: manidevasani
      POSTGRES_PASSWORD: Manikanta
      POSTGRES_DB: chatapp
    networks:
    - network


  chatapp:
    build:
      context: /home/ubuntu/Docker/
    ports:
    - "80:8000"
    hostname: chatproject
    container_name: chatproject
    networks:
    - network
    depends_on: 
    - db


  nginx:
    build:
      context: /home/ubuntu/Docker/nginx/
    ports:
    - "8000:80"
    hostname: nginx
    networks:
    - network
    depends_on:
    - chatapp


networks:
  network:
    driver: bridge  
